//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnUpsell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string MortgageType { get; set; }
        public int PropertyValue { get; set; }
        public int LoanValue { get; set; }
        public string MortgageTerm { get; set; }
        public string RateTerm { get; set; }
        public string Repayment { get; set; }
        public string PropertyType { get; set; }
        public int CurrentDebt { get; set; }
        public string EmploymentStatus { get; set; }
        public int AnnnualIncome { get; set; }
        public string CreditHistory { get; set; }
        public bool MissedAnyLoan { get; set; }
        public bool HadBankrupcy { get; set; }
        public bool AppliedForIVA { get; set; }
        public bool HadACCJ { get; set; }
    }
}
